### ISSUE TITLE
Won't Compile

### ISSUE THREAD

**Issue by philipamour** [agrinman/sift-ios#4]
`No such module 'AwesomeCache'`

I would strongly suggest to add build instructions for non-iOS-developers

**Comment by agrinman** [comment]
Yep -- I'm working on guide!

`AwesomeCache` is a git submodule, so you want to do `git submodule update --init --recursive` to pull in that code.

**Comment by helmut72** [comment]
I get this message:

> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

**Comment by agrinman** [comment]
@helmut72 It looks like you have not setup ssh keys for github? See this https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

**Comment by helmut72** [comment]
Sorry, you're right. Overseen SSH because I've only used HTTPS for Github. Now it compiles and runs without any problems. Thank you!

How can I see if the network content filter is enabled/disabled? On the switch in your App? Is it completely removed if I remove the App? In the VPN settings Sift asked for adding the network content filter, but it's not visible after accepting it.
